import exceptions

print(exceptions.greet('Student'))